//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationUser()
        {
            this.Bookings = new HashSet<Booking>();
            this.Drivers = new HashSet<Driver>();
            this.PaymentCards = new HashSet<PaymentCard>();
            this.Redemptions = new HashSet<Redemption>();
        }
    
        public string Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Roles { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<int> TwoStepVerification { get; set; }
        public Nullable<int> EmailVerification { get; set; }
        public Nullable<int> IsBan { get; set; }
        public string BanReason { get; set; }
        public Nullable<int> OtpCode { get; set; }
        public Nullable<System.DateTime> OtpCreatedTime { get; set; }
        public Nullable<int> RewardPoints { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentCard> PaymentCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redemption> Redemptions { get; set; }
    }
}
