//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentCard()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public string Id { get; set; }
        public string CardNumber { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> CVV { get; set; }
        public string UserId { get; set; }
        public string CardType { get; set; }
        public Nullable<int> IsDefault { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
