//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public string BookingId { get; set; }
        public string ReviewText { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
