//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestBook
    {
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string CustomerPhone { get; set; }
        public string Destination { get; set; }
        public string Note { get; set; }
        public string DriverName { get; set; }
        public string DriverGender { get; set; }
        public string DriverID { get; set; }
        public string DriverPhone { get; set; }
        public Nullable<int> DriverAge { get; set; }
        public string DriverRace { get; set; }
        public string DriverLicense { get; set; }
        public string RentalPurpose { get; set; }
    }
}
