//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTrip
    {
        public string Id { get; set; }
        public string Pickup_point { get; set; }
        public string Pickup_state { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Dropoff_point { get; set; }
        public string Dropoff_state { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CarPlateNo { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
