//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRewardPointsView
    {
        public string Username { get; set; }
        public Nullable<int> RewardPoints { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> PointsRemaining { get; set; }
    }
}
